export const apiRoutes = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    logout: "/auth/logout",
    fetchMe: "/auth/me",
    forgotPassword: "/auth/forgot-password",
    forgotPasswordResend: "/auth/resend-forgot-password",
    resetPassword: "/auth/reset-password",
  },
  projects: {
    getAll: "/projects",
    getById: "/projects/:id",
    create: "/projects",
    update: "/projects/:id",
    delete: "/projects/:id",
  },
  documents: {
    getAll: "/documents",
    getById: "/documents/:id",
    create: "/documents",
    update: "/documents/:id",
    delete: "/documents/:id",
  },
  commits: {
    getAll: "/commits",
    getById: "/commits/:id",
    create: "/commits",
    update: "/commits/:id",
    delete: "/commits/:id",
  },
  versions: {
    getAll: "/versions",
    getById: "/versions/:id",
    create: "/versions",
    update: "/versions/:id",
    delete: "/versions/:id",
  },
  users: {
    getAll: "/users",
    getById: "/users/:id",
    create: "/users",
    update: "/users/:id",
    delete: "/users/:id",
  },
  collaborators: {
    getByProject: "/projects/:projectId/collaborators",
    invite: "/projects/:projectId/collaborators/invite",
    remove: "/projects/:projectId/collaborators/:userId",
    update: "/projects/:projectId/collaborators/:userId",
  },
};